export { default as AppAbout } from './about'
export { default as AppFaq } from './faq'
export { default as AppContact } from './contact'
export { default as AppMain } from './main'
export { default as AppGallery } from './gallery'
export { default as AppCareer } from './career'
export { default as AppService } from './services'